import type { Metadata } from "next";
import "./globals.css";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { ToastContainer } from 'react-toastify'
import 'react-toastify/dist/ReactToastify.css'

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body data-new-gr-c-s-check-loaded="14.1226.0" data-gr-ext-installed=""  cz-shortcut-listen="true">

        {children}
        <ToastContainer position="bottom-right" />
      </body>
    </html>
  );
}
